FROM nginx 
RUN  rm -rf /usr/share/nginx/html/index.html 
RUN echo "<h1>Hi, I am from APP-1 </h1>" > /usr/share/nginx/html/index.html  

FROM nginx 
RUN rm -rf /usr/share/nginx/html/index.html 
RUN echo "<h1>Hi, I am from app-1</h1>" > /usr/share/nginx/html/index.html 